sudo: required
git:
  depth: 3
services:
  - docker
matrix:
  include:
    - env:
      - docker_image="lhofmann/paraview-superbuild:5.6.0"
      - download_url="https://www.paraview.org/files/v5.6/ParaView-5.6.0-MPI-Linux-64bit.tar.gz"
      - release_name="ParaView-5.6.0-MPI-Linux-64bit"
    - env:
      - docker_image="lhofmann/paraview-superbuild:5.6.0-osmesa"
      - download_url="https://www.paraview.org/files/v5.6/ParaView-5.6.0-osmesa-MPI-Linux-64bit.tar.gz"
      - release_name="ParaView-5.6.0-osmesa-MPI-Linux-64bit"
    - env:
      - docker_image="lhofmann/paraview-superbuild:5.6.0-egl"
      - download_url="https://github.com/lhofmann/paraview-superbuild-docker/releases/download/5.6.0/ParaView-5.6.0-egl-MPI-Linux-64bit.tar.gz"
      - release_name="ParaView-5.6.0-egl-MPI-Linux-64bit"
script:
  - docker pull ${docker_image}
  - chmod -R 777 .
  - docker run -itd --name build --volume="`pwd`:/mnt:rw" ${docker_image}  
  - docker exec build /usr/bin/scl enable devtoolset-4 -- cmake -H/mnt/shared/example -B/mnt/shared/build
  - docker exec build cmake --build /mnt/shared/build -- -j2
  - wget "${download_url}" -O ${release_name}.tar.gz
  - tar xzf ${release_name}.tar.gz
  - cp shared/build/libExamplePlugin.so ${release_name}/lib/plugins/
  - ./${release_name}/bin/pvpython .travis.test.py
